### ISSUE TITLE
Placeholder doesn't work

### ISSUE THREAD

**Issue by Nardann** [Ehhthan/HappyHud-Issues#50]
## With first code : 
```
hud-background:
  layers:
    player-text:
      text: "%player_name%"
      font: "default"
      outlined: true
      offset:
        x: -3
        y: -4
```
### Ingame display
![image](https://user-images.githubusercontent.com/94087736/233071637-d21ef304-4feb-4678-9722-15c512ade619.png)

## With second code : 
```
hud-background:
  layers:
    player-text:
      text: "%player_name-value%"
      font: "default"
      outlined: true
      offset:
        x: -3
        y: -4
```
### Ingame display
![image](https://user-images.githubusercontent.com/94087736/233071933-2e2084a7-80e6-4b0c-b5f2-d8bbe99a3ee4.png)
