### ISSUE TITLE
Hud sometimes shift over when new layouts are added

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#7]
By adding multiple layers, it seems some have a tendency to move all other layers and elements around
Only real consistency ive found are when the `text` property contains a placeholder that is turned into something else.

For example this, where the whistle placeholder is replaced with a unicode tied to a font file (cant use icon as it needs to change with layer)
```yml
mineinabyss-layer:
  layers:
    text:
      text: "%mineinabyss_whistle% %mineinabyss_layer%"
      font: "mineinabyss-outline"
      offset:
        x: 0
        y: 0
```

This one is also one that consistently pushes all other hud elements, so seemingly it must be unicodes in text field?
```yml
mineinabyss-orthbanking-coins:
  layers:
    text:
      text: "%mineinabyss_orthbanking_coins%"
      font: "orthbanking"
      offset:
        x: 0
        y: 0
```

showcase of the to above (middle and bottom command blocks) and other layout that dont affect other layout positions

https://user-images.githubusercontent.com/62521371/186968425-fb77c7dd-faa7-42e9-b4c3-609f8a50ba11.mp4
