### ISSUE TITLE
Reversed Function Asset not working properly with 0.5 Scale

### ISSUE THREAD

**Issue by DrakerSAN** [Ehhthan/HappyHud-Issues#77]
So currently everything looks fine here, 

![Screenshot 2023-08-27 163652](https://github.com/Ehhthan/HappyHud-Issues/assets/143358197/57d20428-4073-45a4-9886-315f7c6f98ad)

```
outline-mana:
  layers:
    fill:
      texture:
        path: assets/ouroborionrpg/mana_bar.png
      scale: 0.5
      offset:
        x: 0
        y: 0
      function:
        listener: mana
        increment: 10
        orientation: horizontal
    outline:
      texture:
        path: assets/ouroborionrpg/outline_mana_bar.png
      scale: 0.5
```

but I want the mana bar to deplete in the other direction, so I will use the reversed function...

```
outline-mana:
  layers:
    fill:
      texture:
        path: assets/ouroborionrpg/mana_bar.png
      scale: 0.5
      offset:
        x: 0
        y: 0
      function:
        listener: mana
        increment: 10
        orientation: horizontal
        reversed: true
    outline:
      texture:
        path: assets/ouroborionrpg/outline_mana_bar.png
      scale: 0.5
```

![Screenshot 2023-08-27 163736](https://github.com/Ehhthan/HappyHud-Issues/assets/143358197/402da5bc-9726-4630-9d3f-435cdddc058b)

and for some reason it goes off unto the right direction, but weird thing is if I remove the 0.5 Scale it stays at its fixed point and depletes how I want it to, only thing I can think of is the 0.5 Scale is working weirdly.

```
outline-mana:
  layers:
    fill:
      texture:
        path: assets/ouroborionrpg/mana_bar.png
      offset:
        x: 0
        y: 0
      function:
        listener: mana
        increment: 10
        orientation: horizontal
        reversed: true
    outline:
      texture:
        path: assets/ouroborionrpg/outline_mana_bar.png
      scale: 0.5
outline-left:
  layers:
    outline:
      texture:
        path: assets/ouroborionrpg/outline_left.png
      scale: 0.5
      offset:
        x: 0
        y: 0
```

![Screenshot 2023-08-27 164355](https://github.com/Ehhthan/HappyHud-Issues/assets/143358197/1d3231c2-6078-492d-833e-5a73f636457b)
