### ISSUE TITLE
Allow papi placeholders to be used for an asset's color

### ISSUE THREAD

**Issue by eyasu4198** [Ehhthan/HappyHud-Issues#82]
Essentially, I want to be able to use placeholders for an asset's color so that I can let the players choose what color they want their ui to show up as.

At the moment, attempting to do so returns a "Color does not exist" error upon reload.

**Comment by Ehhthan** [comment]
Currently color does not parse placeholders. Adding this as a possible future enhancement.

**Comment by YKDZ** [comment]
I think my suggestion is very similar, anyway: I'd like to make the texture path support placeholders as well.

It may be something like this:

```
skill-casting-bar:
  layers:
    skill:
      conditions:
        - placeholder{ph=%wizardry_ifInSkillCasting%;v=true} true hide
        #- placeholder{ph=%wizardry_wandBoundCurrnet%;v=FIREBALL} false texture assets/skill-casting-bar/mage/icon_fireball
      texture:
        path: assets/skill-icon/icon_%wizardry_wandBoundCurrentLower%.png
      offset:
        x: 2
        y: -2
```
